export const english = {
  ProfileStrength: 'Profile strength:',
  complete: 'complete',
  RecruitersFrom: ' Recruiters notice you from',
  PendingActions: 'Pending Actions',
  AboutSocialProfile: 'About Social Profile',
  AboutEducation: 'About Your Education',
  AddEducation: 'Add Education',
  Balance: 'Balance',
  SkipNow: 'Skip Now',
  subtitle: 'Password for your account will also be sent on this email.',
  WelcomeFinploy: 'Welcome to Finploy',
  part1: `Transferwise (Recommended) Transferwise may charge additional fee, take 4 days`,
  WithdrawFunds: 'Withdraw Funds',
  Paypal: 'Paypal',
  WhatsName: 'What is yor name',
  WhatIdentity: 'What is your identity?',
  recentlyGraduated: 'I am a student or have recently graduated',
  part2: 'Transferwise may charge additional fee, take 4 days',
  part3sub: 'Stribe (US Bank only) 4 days',
  part3sub2: `Stribe (US Bank only) Transferwise may charge additional fee,
  take 4 days`,
  AddAccount: 'Add Account',
  Skills: 'Skills',
  PleaseNumber: 'Please enter your registered mobile number',
  PleaseNumberAtRegister: 'Please enter your mobile number',
  AddSkills: 'Add Skills',
  AddWorkExperience: 'Add work Experience',
  AboutWorkExperience: 'About Work Experience',
  AboutIdealJob: 'About Ideal Job',
  AboutYourSkills: 'About Your Skills',
  AboutYourProfile: 'About Your Profile',
  Social: 'About Social Profile',
  JobAlerts: 'Job Alerts',
  CreateAlert: ' Create a free job alert',
  CreateInbox:
    ' Create a free job alert and get notified directly in your inbox',
  ReferEarn: 'Refer & Earn',
  Money: '3,00,000 INR',
  MobileNumber: 'Mobile Number',
  linkAccount: 'Please sign into your linkedin account',
  PhoneNumber: 'Phone Number',
  PhoneSub: 'Please enter your phone number',
  ReceivedOTP: 'Received an OTP?',
  OtpSubTitle: 'Please type the otp sent to you on your mobile phone',
  UpdateNotificationSettings: 'Update Notification Settings',
  ProfilePrivacySettings: 'Profile Privacy settings',
  LoginAs: ' Login as',
  Candidate: 'Candidate',
  Deactivating: `Deactivating your account will be disabled your profile. Youcan not apply for any job.`,
  Employer: 'Employer',
  Partner: 'Partner',
  Skip: 'Skip',
  or: 'or',
  WhichCityDo: `Which City do you live in?`,
  WhatsYourWorkEx: `Do you have work experience?`,
  employmentWas: `Your last work employment type was?`,
  headingProfile1: `Thanks for registering with us, Complete your profile and find right job with us.`,
  totalWorkExperience: `What's your total work experience `,
  NoticePeriod: 'Please let us know your Notice Period:',
  SearchJob: 'Search Jobs',
  AllJobs: 'All Jobs',
};
